version: '3.7'
services:
  hakai-profile-qc:
    image: ghcr.io/hakaiinstitute/hakai_ctd_qc:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    env_file:
      - .env