version: '3.7'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    environment:
      - "HAKAI_API_CREDENTIALS=${HAKAI_API_CREDENTIALS}"
    ports:
      - '19999:19999'
