name: hakai_qc
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - pip
  - tqdm
  - pandas
  - pyyaml
  - tqdm==4.64.0
  - xarray==2022.3.0
  - ioos_qc==2.0.1
  - gsw
  - pip:
      - sentry_sdk
      - hakai_api
      - git+https://github.com/HakaiInstitute/ocean-data-parser.git
      - -e .
