# QC parameters
QARTOD_TESTS_CONFIGURATION_PATH: ${PACKAGE_PATH}/config/hakai_ctd_profile_qartod_test_config.json
HAKAI_TESTS_CONFIGURATION_PATH: ${PACKAGE_PATH}/config/hakai_ctd_profile_tests_config.json
GREY_LIST_PATH: ${PACKAGE_PATH}/HakaiProfileDatasetGreyList.csv
STATION_LIST_PATH: ${PACKAGE_PATH}/HakaiStationLocations.csv

# Hakai API Endpoints Definition
UPDATE_SERVER_DATABASE: false
CTD_CAST_CHUNKSIZE: 300
HAKAI_API_SERVER_ROOT: https://goose.hakai.org/api
CTD_CAST_ENDPOINT: "ctd/views/file/cast"
CTD_CAST_DATA_ENDPOINT: "ctd/views/file/cast/data"
CTD_CAST_QC_ENDPOINT: "eims/views/output/ctd_qc"
HAKAI_STATIONS_ENDPOINT: "eims/views/output_sites"

# NETCDF Attributes
HAKAI_CTD_ATTRIBUTES: ${PACKAGE_PATH}/config/hakai_profile_default_attributes.json

# Flag Conventions
FLAG_CONVENTIONS:
    Hakai:
        AV: accepted_value
        MV: missing_value
        SVC: suspisious_value_cautious
        SVD: suspisious_value_discard
        NA: not_available
    QARTOD:
        1: GOOD
        2: UNKOWN
        3: SUSPECT
        4: FAIL
        9: MISSING
    direction_flag:
        d: downward
        c: stable
        u: upward


# IOOS QC COORDS Mapping
ioos_qc_coords_mapping:
    tinp: "measurement_dt"
    zinp: "depth"
    lon: "longitude"
    lat: "latitude"

RESEARCH_CTD_VARIABLES: [
    "depth",
    "pressure",
    "temperature",
    "salinity",
    "conductivity",
    "spec_cond",
    "turbidity",
    "flc",
    "dissolved_oxygen_ml_l",
    "dissolved_oxygen_percent",
    "rinko_do_ml_l",
    "par",
    "c_star_at"
]

# Subset of variables to download from CTD_CAST_DATA_ENDPOINT
CTD_VARIABLES: [
        "ctd_file_pk",
        "ctd_cast_pk",
        "hakai_id",
        "ctd_data_pk",
        "filename",
        "device_model",
        "device_sn",
        "device_firmware",
        "file_processing_stage",
        "work_area",
        "cruise",
        "station",
        "cast_number",
        "station_longitude",
        "station_latitude",
        "distance_from_station",
        "latitude",
        "longitude",
        "location_flag",
        "location_flag_level_1",
        "process_flag",
        "process_flag_level_1",
        "start_dt",
        "bottom_dt",
        "end_dt",
        "duration",
        "start_depth",
        "bottom_depth",
        "target_depth",
        "drop_speed",
        "vessel",
        "direction_flag",
        "measurement_dt",
        "descent_rate",
        "conductivity",
        "conductivity_flag",
        "conductivity_flag_level_1",
        "temperature",
        "temperature_flag",
        "temperature_flag_level_1",
        "depth",
        "depth_flag",
        "depth_flag_level_1",
        "pressure",
        "pressure_flag",
        "pressure_flag_level_1",
        "par",
        "par_flag",
        "par_flag_level_1",
        "flc",
        "flc_flag",
        "flc_flag_level_1",
        "turbidity",
        "turbidity_flag",
        "turbidity_flag_level_1",
        "ph",
        "ph_flag",
        "ph_flag_level_1",
        "salinity",
        "salinity_flag",
        "salinity_flag_level_1",
        "spec_cond",
        "spec_cond_flag",
        "spec_cond_flag_level_1",
        "dissolved_oxygen_ml_l",
        "dissolved_oxygen_ml_l_flag",
        "dissolved_oxygen_ml_l_flag_level_1",
        "rinko_do_ml_l",
        "rinko_do_ml_l_flag",
        "rinko_do_ml_l_flag_level_1",
        "dissolved_oxygen_percent",
        "dissolved_oxygen_percent_flag",
        "dissolved_oxygen_percent_flag_level_1",
        "oxygen_voltage",
        "oxygen_voltage_flag",
        "oxygen_voltage_flag_level_1",
        "c_star_at",
        "c_star_at_flag",
        "c_star_at_flag_level_1",
        "sos_un",
        "sos_un_flag",
        "sos_un_flag_level_1",
        "backscatter_beta",
        "backscatter_beta_flag",
        "backscatter_beta_flag_level_1",
        "cdom_ppb",
        "cdom_ppb_flag",
        "cdom_ppb_flag_level_1"
    ]

# Ignored station list
IGNORED_HAKAI_STATIONS: [
        "AB1",
        "BED1",
        "BED10",
        "BED3",
        "BED4",
        "BED5",
        "BED6",
        "BED7",
        "BED8",
        "BED9",
        "CP1",
        "CP2",
        "FCC1",
        "HER1",
        "HER2",
        "HER3",
        "HER4",
        "HER5",
        "MC1",
        "RC1",
        "RC2",
        "RC3"
    ]
