name: Production QC Cron Job
on:
  schedule:
    - cron: '* * * * *'
jobs:
  run-qc:
    name: Run QC cron job on Hecate Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy main
        run: caprover deploy --caproverUrl https://captain.server.hak4i.org --appToken ${{ secrets.CAPROVER_TOKEN_PRODUCTION }} --branch 'main' --appName hakai-profile-qc-production
