name: Rebuild Hakai Production CTD QC
on:
  workflow_dispatch:
jobs:
  run-qc:
    name: Update QC on Production Hakai Database
    runs-on: ubuntu-latest
    environment:
      name: main
      url: https://captain.server.hak4i.org/#/apps/details/hakai-profile-qc-hakai-production-rebuild
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy main
        run: caprover deploy --caproverUrl https://captain.server.hak4i.org --appToken ${{ secrets.CAPROVER_TOKEN_REBUILD_HAKAI_PRODUCTION }} --branch 'main' --appName hakai-profile-qc-hakai-production-rebuild
