name: Rerun full auto qc on hakai production database
on:
  workflow_dispatch:
jobs:
  run-qc:
    name: Update QC on Goose Database
    runs-on: ubuntu-latest
    environment:
      - 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy main
        run: caprover deploy --caproverUrl https://captain.server.hak4i.org --appToken ${{ secrets.CAPROVER_TOKEN_REBUILD_HAKAI_PRODUCTION }} --branch 'main' --appName hakai-profile-qc-hakai-production-rebuild
