name: Install package, run linter and run test suite
on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - hakai_profile_qc/**
      - tests/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  miniconda:
    name: Run linter and test suite
    runs-on: ubuntu-latest
    env:
      HAKAI_API_SERVER_ROOT: https://goose.hakai.org/api
      HAKAI_API_TOKEN: ${{ secrets.HAKAI_API_TOKEN }}
      RUN_TEST_SUITE": true
      UPDATE_SERVER_DATABASE: true
      ENVIRONMENT: github
      SENTRY_DSN: null
    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install package locally
        run: |
          pip install poetry ruff && \
          poetry config virtualenvs.create false && \
          poetry install --with dev
      - name: Run ruff
        run: poetry run ruff check --output-format=github .
      - name: Pytest
        run: pytest .
      - name: Run test suite on Hakai Goose
        run: python hakai_profile_qc --test-suite
