name: Install package, run linter and run test suite
on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - hakai_profile_qc/**
      - tests/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  miniconda:
    name: Run linter and test suite
    runs-on: ubuntu-latest
    env:
      HAKAI_API_SERVER_ROOT: https://goose.hakai.org/api
      HAKAI_API_TOKEN: ${{ secrets.HAKAI_API_TOKEN }}
      RUN_TEST_SUITE": true
      UPDATE_SERVER_DATABASE: true
      ENVIRONMENT: github
      SENTRY_DSN: null
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install package locally
        run: pip install poetry ruff && poetry install --with dev
      - name: Pytest
        run: poetry run pytest .
      - name: Run test suite on Hakai Goose
        run: poetry run python hakai_profile_qc --test-suite
